kinghy:
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: web-framework-cs
  dashscope:
    api-key: ${DASHSCOPE_API_KEY}
  websearch:
    api-key: ${SEARCHAPI_API_KEY}